name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Turbo Repo
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      # - name: Build
      #   run: yarn build
